<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="458" started-at="2015-05-10T17:32:51Z" finished-at="2015-05-10T17:32:51Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="458" started-at="2015-05-10T17:32:51Z" finished-at="2015-05-10T17:32:51Z">
      <class name="com.FCI.SWE.Controller.UserControllerTest">
        <test-method status="PASS" signature="AcceptFriendRequest()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="AcceptFriendRequest" duration-ms="56" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AcceptFriendRequest -->
        <test-method status="FAIL" signature="CreatePage()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="CreatePage" duration-ms="16" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<Page [Has Been Created Successfully]> but was:<Page [With Same Name Has Been Created Before]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<Page [Has Been Created Successfully]> but was:<Page [With Same Name Has Been Created Before]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.FCI.SWE.Controller.UserControllerTest.CreatePage(UserControllerTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreatePage -->
        <test-method status="FAIL" signature="LikePage()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="LikePage" duration-ms="12" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <exception class="junit.framework.ComparisonFailure">
            <message>
              <![CDATA[expected:<...n Liked Successfully[].> but was:<...n Liked Successfully[ ].>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.ComparisonFailure: expected:<...n Liked Successfully[].> but was:<...n Liked Successfully[ ].>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.FCI.SWE.Controller.UserControllerTest.LikePage(UserControllerTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LikePage -->
        <test-method status="PASS" signature="MyHashStatstics()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="MyHashStatstics" duration-ms="17" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- MyHashStatstics -->
        <test-method status="PASS" signature="SendFriendRequest()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="SendFriendRequest" duration-ms="27" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendFriendRequest -->
        <test-method status="PASS" signature="SendMsg()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="SendMsg" duration-ms="61" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SendMsg -->
        <test-method status="FAIL" signature="login()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="login" duration-ms="225" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<OutboundJaxrsResponse{status=200, reason=OK, hasEntity=true, closed=false, buffered=false}> but was:<OutboundJaxrsResponse{status=200, reason=OK, hasEntity=true, closed=false, buffered=false}>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<OutboundJaxrsResponse{status=200, reason=OK, hasEntity=true, closed=false, buffered=false}> but was:<OutboundJaxrsResponse{status=200, reason=OK, hasEntity=true, closed=false, buffered=false}>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:86)
	at com.FCI.SWE.Controller.UserControllerTest.login(UserControllerTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:352)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:347)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="response()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTest@6bfd472]" name="response" duration-ms="15" started-at="2015-05-10T19:32:51Z" finished-at="2015-05-10T19:32:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- response -->
      </class> <!-- com.FCI.SWE.Controller.UserControllerTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
